#ifndef __WORDBANK_H__
#define __WORDBANK_H__

#include <avr/pgmspace.h>
#define LENG(_x) sizeof(_x)/sizeof(_x[0])

const char words5[][6] PROGMEM={
  "APPLE","BEACH","CHIPS","DREAM","EARTH","PLANT","SMILE","CLOUD","FLAME","OCEAN","RIVER","STONE","STORM","TREES",
  "WATER","PHONE","MOUSE","BREAD","CABLE","CHAIR","CRATE","GRASS","GREEN","SOLAR","BLOOM","FROST","SHORE","SPACE",
  "PRINT","STATE","LABEL","STORE","FIRST","DRINK","TRUCK","CLOCK","GLASS","KNIFE","LIGHT","PAPER","PLATE","RADIO",
  "BOARD","BRUSH","FLASK","FRAME","MOTOR","TOWEL","VALVE","LEMON","MANGO","PEACH","SUGAR","SPOON","SPICE","GRAPE",
  "SAUCE","PIZZA","BERRY","HONEY","ROAST","CREAM","FLOUR","BREAK","BUILD","CATCH","DRIVE","GLIDE","JUMPY","LAUGH",
  "MATCH","REACH","SHINE","STAND","THINK","WRITE","START","BRAVE","CLEAN","CLEAR","FRESH","GREAT","HAPPY","HEAVY",
  "LIGHT","QUICK","SHARP","SMART","SWEET","WHITE","YOUNG","BLOCK","BYTES","FLASH","LOGIC","PANEL","PIXEL","POWER",
  "PULSE","RESET","SHIFT","SIGMA","STACK","TRACK","WIRES","ALARM","ANGEL","ARROW","AUDIO","BADGE","BRICK","BRING",
  "CANDY","CHEST","CHIEF","COACH","COAST","COINS","CROWN","DANCE","DEPTH","DIARY","EXTRA","FAIRY","FEVER","FIELD",
  "FLUID","FOCUS","FORCE","FRONT","FRUIT","GIANT","GLOBE","GLOVE","GRAND","GUIDE","HOTEL","HOUSE","IMAGE","INDEX",
  "INPUT","JUICE","LASER","LUNAR","MARCH","MODEL","MONEY","MONTH","MUSIC","NIGHT","NOISE","NORTH","PUNCH","ROUND",
  "ROUTE","SCALE","SCENE","SCORE","SHARK","SLEEP","SMOKE","SOUTH","SOUND","TRAIN","TWICE","VOICE","WATCH","WHEEL",
  "WORLD","ZEBRA","ACTOR","MUGIN","MUGEN","HUGIN","BURQA","NYMPH","OUIJA","VOZHD","WAQFS","IAMBI","MACAW","OKAPI",
};

const char words6[][7] PROGMEM={
  "CAMERA","BOTTLE","BUTTON","CHARGE","PENCIL","HEATER","BANNER","WANDER","CRATER","MIRROR","MARKER",
  "ACTION","ANIMAL","ATTACK","AUTUMN","BARKED","BASKET","BEAUTY","BEAVER","BEFORE","BELONG","PHOTOS",
  "BRANCH","BRIDGE","BRIGHT","CASTLE","CATCHS","CHANCE","CHURCH","CIRCLE","CLEVER","COFFEE","CORNER",
  "CREDIT","DANGER","DECIDE","DEGREE","DOCTOR","DOLLAR","DRAGON","DRIVER","ENGINE","ESCAPE","EXPERT",
  "FACTOR","FAMILY","FARMER","FINGER","FLIGHT","FLOWER","FOREST","FREEZE","GARDEN","GLANCE","GUITAR",
  "HAMMER","HANDLE","HARBOR","HEAVEN","HOLLOW","HUNTER","INSECT","ISLAND","JACKET","SOCKET","JUNGLE",
  "KITTEN","NORDIC","LEADER","LIQUID","LIZARD","MONKEY","THANOS","MOTHER","NATURE","NUMBER","OFFICE",
  "ORANGE","OXYGEN","PACKET","PALACE","PERSON","PLANET","POCKET","POWDER","PRINCE","PRISON","PUZZLE",
  "WIGGLE","RABBIT","ROCKET","RUBBER","SADDLE","SAFETY","SAILOR","SAMPLE","SCREEN","SHADOW","SILVER",
  "SENSOR","TYRANT","PARROT","WALRUS","WHEELS","VISION","OBJECT","LOCATE","GALAXY","SECOND","SONDER",
  "FUDGEL","WORDLE","BLITHE","ACUMEN","ZEALOT","MIASMA","CHRISM","NIMBLE","SCHIST","UMLAUT","COCCYX",
};

const char words7[][8] PROGMEM={
  "PICTURE","MONITOR","PITCHER","LABELER","SANCTUS","COASTER","POPCORN","CHEETAH","LEOPARD",
  "BATTERY","CHASSIS","PROJECT","PLASTIC","HANDSAW","PRINTER","SPRAYER","QUALIFY","QUALITY",
  "ACADEMY","ACCOUNT","ACIDITY","ADDRESS","AGAINST","ALCOHOL","ALREADY","ANALYZE","ANCIENT",
  "ANXIETY","ARRANGE","ARTICLE","ATTEMPT","ATTRACT","BALANCE","BARGAIN","BEDROOM","BENEFIT",
  "BLANKET","BRAVERY","BREATHE","BUILDER","CABINET","CALCIUM","CAPTAIN","CAPSULE","CARAVAN",
  "CENTURY","CHAMBER","CHANNEL","CHAPTER","CHICKEN","CIRCUIT","COLLEGE","COMFORT","COMMAND",
  "COMPANY","CONCERT","CONTROL","COOKING","COUNTER","COUNTRY","CRITICS","CULTURE","CURRENT",
  "CURTAIN","DIAMOND","DIGITAL","DISCUSS","DISEASE","DISPLAY","DIVORCE","DYNAMIC","EASTERN",
  "ECONOMY","ELEMENT","EMERALD","EMPEROR","EVENING","EXACTLY","EXAMPLE","EXCITED","EXCLUDE",
  "FACULTY","FAILURE","FANTASY","FASHION","FEATURE","FEDERAL","FESTIVE","FICTION","FIFTEEN",
  "FINALLY","FINANCE","FOREVER","FORWARD","FREEDOM","GALLERY","GARMENT","GATEWAY","GENERAL",
  "GLACIER","LAUGHED","GOGGLES","GORILLA","GRAVITY","GROCERY","HALFWAY","HAMMOCK","HARVEST",
  "BRUSQUE","ERUDITE","ASCETIC","DEBACLE","ALPHARD","PERFECT","DIVIDED","SEQUOIA","SORGHUM",
};

const char words8[][9] PROGMEM={

};

// word count
const uint16_t WC5=LENG(words5); 
const uint16_t WC6=LENG(words6);
const uint16_t WC7=LENG(words7); 
// const size_t WC8=LENG(words8);

#endif